
###
### Required configuration
###

# A name for the plugin
name: Example

# Type of the plugin. The only possible value for now is "service".
type: service

# Full class name of class implementing Neucore\Plugin\ServiceInterface.
phpClass: Vendor\Neucore\Plugin\Name\Service

# PHP namespace that should be loaded by the PSR-4 autoloader.
psr4Prefix: Vendor\Neucore\Plugin\Name

# Relative (to this file) path to the directory containing the classes of the above namespace.
psr4Path: src

# Defines if this service allows only one account per player instead of one per character.
oneAccount: true

# List of available account properties, possible values: username, password, email, status, name
properties:
  - username
  - password
  - email
  - status
  - name

# If this is not enabled and the account contains a password (see properties), the user will be able to see
# it only once after it is reset (see actions).
showPassword: false

# List of actions, possible values: update-account, reset-password
actions:
  - update-account
  - reset-password


###
### Optional configuration
###

# List of link buttons. Placeholders for URL: {plugin_id}, {username}, {password}, {email}
URLs:
  -
    url: /plugin/{plugin_id}/action
    title: Example
    target: _self

# Text above the list of accounts (supports multiline text).
textTop:

# Text below account table (supports multiline text).
textAccount:

# Text below the registration form/button (supports multiline text).
textRegister:

# Text below an account with status "pending" (supports multiline text).
textPending:

# Additional configuration for the plugin (supports multiline text).
configurationData:
